services:
  relaychat-client:
    container_name: relaychat-client-staging
    build:
      context: ../..
      dockerfile: RelayChat.Client/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    ports:
      - "27060:8080"
    restart: unless-stopped
