services:
  relaychat-client:
    container_name: relaychat-client-staging
    image: ghcr.io/royalscribblz/relaychat-client:latest-staging
    ports:
      - "27060:8080"
    restart: unless-stopped
